=== ShibuKuppelanLearning/XML/MarshallingAndUnMarshalling/src/com/xml/docs/countryDetails.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="language" type="xs:string"/>
                            <xs:element name="capital" type="xs:string"/>
                            <xs:element name="states" type="states"/>
                        </xs:sequence>
                        <xs:attribute name="code" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>            
        </xs:complexType>
    </xs:element> 
    <xs:complexType name="states">
        <xs:sequence>
            <xs:element name="state" maxOccurs="unbounded" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="language" type="xs:string"/>
                        <xs:element name="capital" type="xs:string"/>
                    </xs:sequence>     
                    <xs:attribute name="code" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ShibuKuppelanLearning/XML/MarshallingAndUnMarshalling/src/com/xml/docs/countryDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='countryDetails.xsd'>
    <country code="IN">
        <name>INDIA</name>
        <language>HINDI</language>
        <capital>DELHI</capital>
        <states>
            <state>
                <name>KERALA</name>
                <language>MALAYALAM</language>
                <capital>THIRUVANANTHAPURAM</capital>
            </state>
            
            <state>
                <name>KERALA</name>
                <language>MALAYALAM</language>
                <capital>THIRUVANANTHAPURAM</capital>
            </state>
        </states>
    </country>
</root>
