=== ShibuKuppelanLearning/XML/XMLBasics/src/com/xml/docs/dtd/countryDetails.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/countryDetails.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE root SYSTEM "countryDetails.dtd">

    <root>
    ...
    </root>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT root (country)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT country (name,language,capital,states)+>
<!ATTLIST country
    code CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT language (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT capital (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT states (state)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT state (name,language,capital)+>
<!ATTLIST state
    code CDATA #REQUIRED
  >

=== ShibuKuppelanLearning/XML/XMLBasics/src/com/xml/docs/dtd/countryDetails.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root SYSTEM "countryDetails.dtd">

<root>
    <country code="IN">
        <name>India</name>
        <language>Hindi</language>
        <capital>Delhi</capital>
        <states>
            <state code="KL">
                <name>Kerala</name>
                <language>Malayalam</language>
                <capital>Thiruvananthapuram</capital>
            </state>
            
            <state code="TN">
                <name>Tamilnadu</name>
                <language>Tamil</language>
                <capital>Chennai</capital>
            </state>
        </states>
    </country> 
</root>
